services:
  backend:
    image: storbiic/etl_dashboard-backend:latest 
    ports:
      - "8000:8000"
    environment:
      - FASTAPI_HOST=0.0.0.0
      - FASTAPI_PORT=8000
      - FASTAPI_RELOAD=true
      - LOG_LEVEL=DEBUG
      - UPLOAD_FOLDER=/app/data/uploads
      - PROCESSED_FOLDER=/app/data/processed
      - PIPELINE_OUTPUT_FOLDER=/app/data/pipeline_output
    volumes:
      # Use consistent volume mounting across platforms
      - type: bind
        source: ./data
        target: /app/data
      - type: bind
        source: ./backend
        target: /app/backend
      - type: bind
        source: ./powerbi
        target: /app/powerbi
    networks:
      - etl-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:8000/health || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  frontend:
    image: storbiic/etl_dashboard-frontend:latest 
    ports:
      - "3000:3000"
    environment:
      - FLASK_HOST=0.0.0.0
      - FLASK_PORT=3000
      - FLASK_DEBUG=true
      - FASTAPI_HOST=backend
      - FASTAPI_PORT=8000
      - PROCESSED_FOLDER=/app/data/processed
      - PIPELINE_OUTPUT_FOLDER=/app/data/pipeline_output
    volumes:
      # Use consistent volume mounting across platforms
      - type: bind
        source: ./data
        target: /app/data
      - type: bind
        source: ./frontend
        target: /app/frontend
      - type: bind
        source: ./backend
        target: /app/backend
      - type: bind
        source: ./powerbi
        target: /app/powerbi
    depends_on:
      - backend
    networks:
      - etl-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:5000/ || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

networks:
  etl-network:
    driver: bridge

volumes:
  etl_data:

