name: Validate Docker Compose & Publish Build Info

on:
  push:
    branches:
      - main

jobs:
  validate-compose:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup JFrog CLI
        uses: jfrog/setup-jfrog-cli@v4
        env:
          JF_URL: ${{ vars.JF_URL }}
          JF_ACCESS_TOKEN: ${{ secrets.JF_ACCESS_TOKEN }}

      - name: Validate docker-compose
        run: |
          docker compose config

      - name: Pull Docker images (from Docker Hub)
        run: |
          docker compose pull

      - name: Publish Build Info With JFrog CLI
        env:
          JFROG_CLI_BUILD_NAME: jfrog-docker-build-example
          JFROG_CLI_BUILD_NUMBER: ${{ github.run_number }}
        run: |
          jf rt build-collect-env
          jf rt build-add-git
          jf rt build-publish
